distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.40.97:40901'
distributed.diskutils - INFO - Found stale lock file and directory '/home/ad/alberta/worker-zer4713j', purging
distributed.diskutils - INFO - Found stale lock file and directory '/home/ad/alberta/worker-5r1udm1j', purging
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/work/logiciels/rh7/conda/4.5.4/envs/pangeo_full_201902/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/work/logiciels/rh7/conda/4.5.4/envs/pangeo_full_201902/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/work/logiciels/rh7/conda/4.5.4/envs/pangeo_full_201902/lib/python3.7/site-packages/distributed/process.py", line 173, in _run
    target(*args, **kwargs)
  File "/work/logiciels/rh7/conda/4.5.4/envs/pangeo_full_201902/lib/python3.7/site-packages/distributed/nanny.py", line 511, in _run
    worker = Worker(*worker_args, **worker_kwargs)
  File "/work/logiciels/rh7/conda/4.5.4/envs/pangeo_full_201902/lib/python3.7/site-packages/distributed/worker.py", line 416, in __init__
    File(path))
  File "/work/logiciels/rh7/conda/4.5.4/envs/pangeo_full_201902/lib/python3.7/site-packages/zict/file.py", line 63, in __init__
    os.mkdir(self.directory)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ad/alberta/worker-hic5a7vw/storage'
distributed.nanny - WARNING - Worker process 9855 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.40.97:40901'
distributed.dask_worker - INFO - End worker
